<script lang="ts">
  import { onMount } from "svelte";
  import { initLottoData } from "$lib/stores/lottoStore";
  import NextDrawTable from "$lib/components/NextDrawTable.svelte";
  import ResultTable from "$lib/components/ResultTable.svelte";
  import PowerBallResult from "$lib/components/PowerBallResult.svelte";

  onMount(() => {
    initLottoData();
  });
</script>

<div class="max-w-6xl mx-auto p-4 md:p-8 space-y-12">
  <div class="space-y-4">
    <ResultTable />
  </div>

  <PowerBallResult />

  <div class="space-y-4">
    <NextDrawTable />
  </div>

  <footer class="pt-8 border-t border-gray-100">
    <div
      class="bg-amber-50 border border-amber-200 rounded-lg p-6 max-w-3xl mx-auto text-center"
    >
      <h3
        class="text-amber-800 font-bold mb-2 uppercase tracking-tight text-sm"
      >
        Legal Disclaimer
      </h3>
      <p class="text-amber-700 text-sm leading-relaxed">
        This is a <strong>fun project</strong> and technical demonstration. The predictions
        generated by the AI and frequency models are based on historical entropy
        and do not imply any significant prediction accuracy. Lottery remains a game
        of chance. Please play responsibly.
      </p>
    </div>
  </footer>
</div>
